setwd("/home/gjw/projects/rattle/src")
redo <- function() {source("all.R"); rattle()}
source("rattle.R")
source("zzz.R")
source("associate.R")
source("cluster.R")
source("execute.R")
source("export.R")
source("ada.R")
source("ada_gui.R")
source("nnet.R")
source("log.R")
source("model.R")
#source("paradigm.R")
source("projects.R")
source("rpart.R")
source("random_forest.R")
source("textview.R")
source("data.R")

source("pmml.R")
source("pmml.arules.R")
