cwd <- getwd()
setwd("/home/gjw/projects/rattle/src")
redo <- function() {source("all.R"); rattle()}
source("rattle.R")
source("zzz.R")
source("associate.R")
source("cluster.R")
source("execute.R")
source("export.R")
source("ada.R")
source("ada_gui.R")
source("nnet.R")
source("log.R")
source("model.R")
source("projects.R")
source("rpart.R")
source("random_forest.R")
source("textview.R")
source("data.R")

source("pmml.R")
source("pmml.arules.R")
source("pmml.kmeans.R")
source("pmml.ksvm.R")
source("pmml.lm.R")
source("pmml.nnet.R")
source("pmml.randomForest.R")
source("pmml.rpart.R")
source("pmml.rsf.R")
setwd(cwd)

#library(playwith)
#autoplay(on=TRUE, ask=TRUE)
#rattle(tooltiphack=TRUE)
#rattle()
