## Gnome R Data Miner: GNOME interface to R for Data Mining
##
## Time-stamp: <2006-10-14 20:31:54 Graham Williams>
##
## Textview widget support
##
## Copyright (c) 2006 Graham Williams, Togaware.com, GPL Version 2

setTextview <- function(tv, ..., sep="")
{
  msg <- paste(sep=sep, ...)
  if (length(msg) == 0) msg <-""
  rattleWidget(tv)$getBuffer()$setText(msg)
}

textviewSeparator <- function()
{
  return(paste(sprintf("\n\nGenerated by Rattle %s %s\n", Sys.time(),
                       Sys.info()["user"]),
               paste(rep("=", 70), collapse=""), "\n", sep=""))
}

clearTextview <- function(tv)
{
  rattleWidget(tv)$modifyFont(pangoFontDescriptionFromString("monospace 10"))
  rattleWidget(tv)$getBuffer()$setText("")
}

appendTextview <- function(tv, ..., sep="")
{
  msg <- paste(sep=sep, ...)
  if (length(msg) == 0)
    msg <-""
  else
    msg <- paste(msg, sprintf("\n\nGenerated by Rattle %s %s\n",
                              Sys.time(), Sys.info()["user"]),
                 paste(rep("=", 70), collapse=""), "\n", sep="")
  tv.buf <- rattleWidget(tv)$getBuffer()
  location <- tv.buf$getEndIter()$iter
  tv.buf$insert(location, msg)
}

getTextviewContent <- function(TV)
{
  ## Extract text contents of specified textview and return
  ## it. Designed for use in saveProject.
  
  log.buf <- rattleWidget(TV)$getBuffer()
  start <- log.buf$getStartIter()$iter
  end <- log.buf$getEndIter()$iter
  return(log.buf$getText(start, end))
}

setTextviewContents <- function(TV, text)
{
  ## Set the text contents of the specified textview to the supplied
  ## text. Designed for use in loadProject.

  clearTextview(TV)
  rattleWidget(TV)$setWrapMode("none")
  if (is.null(text))
    rattleWidget(TV)$getBuffer()$setText("")
  else
    rattleWidget(TV)$getBuffer()$setText(text)
}
